
ingress:
  enabled: true
  hosts:
    - coder.k8s-frambozen.nl

  ingressClassName: "traefik"

  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"

  tls:
    - secretName: code-server-tls-prod-cert
      hosts: coder.k8s-frambozen.nl
    
  